<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos_de_baloncesto [
    <!ELEMENT equipos_de_baloncesto (equipo, equipo)>
    <!ELEMENT equipo (nombre, ciudad, entrenador, jugadores)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT entrenador (#PCDATA)>
    <!ELEMENT jugadores (jugador, jugador, jugador, jugador)>
    <!ELEMENT jugador (nombre, posicion)>
    <!ATTLIST jugador
        posicion (Base|Escolta|Alero|Pivot) #REQUIRED
    >
    <!ELEMENT nacionalidad (#PCDATA)>
]>

<equipos_de_baloncesto>
    <equipo>
        <nombre>Depor</nombre>
        <ciudad>A Coru単a</ciudad>
        <entrenador>Pedro</entrenador>
        <jugadores>
            <jugador posicion="Base">
                <nombre>Manolo</nombre>
                <nacionalidad>Espa単ola</nacionalidad>
            </jugador>
            <jugador posicion="Escolta">
                <nombre>Pepe</nombre>
                <nacionalidad>Francesa</nacionalidad>
            </jugador>
            <jugador posicion="Alero">
                <nombre>Giorgio</nombre>
                <nacionalidad>Italiana</nacionalidad>
            </jugador>
            <jugador posicion="Pivot">
                <nombre>Takumi</nombre>
                <nacionalidad>Japonesa</nacionalidad>
            </jugador>
        </jugadores>
    </equipo>

    <equipo>
        <nombre>Parada</nombre>
        <ciudad>Auga</ciudad>
        <entrenador>Luis Dorsal</entrenador>
        <jugadores>
            <jugador posicion="Base">
                <nombre>Pablo</nombre>
                <nacionalidad>Angole単a</nacionalidad>
            </jugador>
            <jugador posicion="Escolta">
                <nombre>Koi</nombre>
                <nacionalidad>Espa単ola</nacionalidad>
            </jugador>
            <jugador posicion="Alero">
                <nombre>Brais</nombre>
                <nacionalidad>Irlandesa</nacionalidad>
            </jugador>
            <jugador posicion="Pivot">
                <nombre>Joseph</nombre>
                <nacionalidad>Americana</nacionalidad>
            </jugador>
        </jugadores>
    </equipo>
</equipos_de_baloncesto>